# Introduction

<div class="alert alert-block alert-warning">
<font color=black><br>

**What?** Results exaploration

<br></font>
</div>

# Import modules

In [1]:
import os, sys
from RightMoveScraper import RightmoveData
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
# URL for all London properties to rent, added in last 24hrs:
url = "https://www.rightmove.co.uk/property-to-rent/find.html?searchType=RENT&locationIdentifier=REGION%5E87490&insId=1&radius=0.0&minPrice=&maxPrice=&minBedrooms=&maxBedrooms=&displayPropertyType=&maxDaysSinceAdded=&sortByPriceDescending=&_includeLetAgreed=on&primaryDisplayPropertyType=&secondaryDisplayPropertyType=&oldDisplayPropertyType=&oldPrimaryDisplayPropertyType=&letType=&letFurnishType=&houseFlatShare="

# Scrape rightmove
scraper = RightmoveData
scraper.__init__
rmd = scraper(url)

URL Validated!
status_code 200
Page No: 42
Scraping page No: 1
status_code 200
Scraping page No: 2
status_code 200
Scraping page No: 3
status_code 200
Scraping page No: 4
status_code 200
Scraping page No: 5
status_code 200
Scraping page No: 6
status_code 200
Scraping page No: 7
status_code 200
Scraping page No: 8
status_code 200
Scraping page No: 9
status_code 200
Scraping page No: 10
status_code 200
Scraping page No: 11
status_code 200
Scraping page No: 12
status_code 200
Scraping page No: 13
status_code 200
Scraping page No: 14
status_code 200
Scraping page No: 15
status_code 200
Scraping page No: 16
status_code 200
Scraping page No: 17
status_code 200
Scraping page No: 18
status_code 200
Scraping page No: 19
status_code 200
Scraping page No: 20
status_code 200
Scraping page No: 21
status_code 200
Scraping page No: 22
status_code 200
Scraping page No: 23
status_code 200
Scraping page No: 24
status_code 200
Scraping page No: 25
status_code 200
Scraping page No: 26
status_code 200
Scraping page No: 27
status_code 200
Scraping page No: 28
status_code 200
Scraping page No: 29
status_code 200
Scraping page No: 30
status_code 200
Scraping page No: 31
status_code 200
Scraping page No: 32
status_code 200
Scraping page No: 33
status_code 200
Scraping page No: 34
status_code 200
Scraping page No: 35
status_code 200
Scraping page No: 36
status_code 200
Scraping page No: 37
status_code 200
Scraping page No: 38
status_code 200
Scraping page No: 39
status_code 200
Scraping page No: 40
status_code 200
Scraping page No: 41
status_code 200
Scraping page No: 42
status_code 400
GOT BAD STATUS CODE!

In [3]:
rmd._results

,price,type,address,url,agent_url,frontPageDescription,postcode,number_bedrooms
0,2525,2 bedroom apartment,Laurel Point,http://www.rightmove.co.uk/properties/11272066...,http://www.rightmove.co.uk/estate-agents/agent...,"A fully furnished and pet friendly, two bedroo...",NaN,2.0
1,500,House share,"North Circular Road, Neasden, London",http://www.rightmove.co.uk/properties/11237712...,http://www.rightmove.co.uk/estate-agents/agent...,Regal Estates are delighted to offer this stun...,NaN,NaN
2,1300,Studio apartment,"Belsize Grove, London, NW3",http://www.rightmove.co.uk/properties/11285849...,http://www.rightmove.co.uk/estate-agents/agent...,A bright and extremely spacious 3rd floor apar...,NW3,0.0
3,3597,2 bedroom flat,39 Westferry Circus London E14,http://www.rightmove.co.uk/properties/11285849...,http://www.rightmove.co.uk/estate-agents/agent...,"Recently refurbished two bedroom, two bathroom...",E14,2.0
4,1400,1 bedroom flat,"Palmers Green, London, N13",http://www.rightmove.co.uk/properties/11273746...,http://www.rightmove.co.uk/estate-agents/agent...,We are proud to offer this delightful large Ed...,N13,1.0
...,...,...,...,...,...,...,...,...
1045,1100,1 bedroom flat,"Geere Road, Stratford, London, E15",http://www.rightmove.co.uk/properties/11281107...,http://www.rightmove.co.uk/estate-agents/agent...,Madison Fox Estate Agent are delighted to offe...,E15,1.0
1046,1800,5 bedroom terraced house,"Trumpington Road, Forest Gate E7",http://www.rightmove.co.uk/properties/11281108...,http://www.rightmove.co.uk/estate-agents/agent...,Madison Fox Estate Agent are pleased to be off...,E7,5.0
1047,1387,Studio apartment,"Paramount Court, Bloomsbury, WC1",http://www.rightmove.co.uk/properties/11281108...,http://www.rightmove.co.uk/estate-agents/agent...,Top floor studio - Newly redecorated - Heating...,WC1,0.0
1048,1240,1 bedroom flat,"Tottenham Road, London",http://www.rightmove.co.uk/properties/11176962...,http://www.rightmove.co.uk/estate-agents/agent...,Property Ref: 11932 - LettingaProperty are del...,NaN,1.0
1049,2349,3 bedroom flat,"Glenroy Street, Shepherds Bush",http://www.rightmove.co.uk/properties/11281102...,http://www.rightmove.co.uk/estate-agents/agent...,This three double bedroom ground floor apartme...,NaN,3.0

In [4]:
rmd._results[rmd._results["price"] == 1475]

,price,type,address,url,agent_url,frontPageDescription,postcode,number_bedrooms
474,1475,1 bedroom flat,"Thane Villas, London N7",http://www.rightmove.co.uk/properties/11284605...,http://www.rightmove.co.uk/estate-agents/agent...,Stunning one bedroom apartment in a mansion bl...,N7,1.0
590,1475,1 bedroom apartment,"Caravel House, Treacle Works, Royal Crest Aven...",http://www.rightmove.co.uk/properties/11284322...,http://www.rightmove.co.uk/estate-agents/agent...,L&Q are proud to present a selection of one-be...,E16,1.0
930,1475,2 bedroom flat,"Perth Road, London, E10",http://www.rightmove.co.uk/properties/11151289...,http://www.rightmove.co.uk/estate-agents/agent...,We are proud to present this delightful and ne...,E10,2.0

In [5]:
rmd._results[rmd._results["price"] == 1475]["url"]

474    http://www.rightmove.co.uk/properties/11284605...
590    http://www.rightmove.co.uk/properties/11284322...
930    http://www.rightmove.co.uk/properties/11151289...
Name: url, dtype: object